variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - deploy
  - publish

lint Helm Charts:
  image:
    name: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/alpine/helm
    entrypoint: ["/bin/sh", "-c"]
  stage: test
  script:
    - helm dependency update
    - helm lint .

test Helm Charts:
  image:
    name: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/alpine/helm
    entrypoint: ["/bin/sh", "-c"]
  stage: test
  script:
    - helm dependency update
    - helm plugin install https://github.com/helm-unittest/helm-unittest
    - helm unittest --color -d .

integration Tests Helm Charts:
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/debian:latest
  services:
    - name: docker:dind
      alias: docker
  script:
    - |
      apk add -U curl
      bash spec/fixtures/create-cluster-with-passbolt.sh

publish:
  stage: publish
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/alpine/helm
  variables:
    REPO_BUCKET: "download.passbolt.com"
    REPO_DIR: "charts"
    CHART_NAME: "passbolt"
  script:
    - |
      export GOOGLE_APPLICATION_CREDENTIALS="$BUCKET_SVC_ACC"
      sh .gitlab-ci/scripts/bin/publishing.sh
  rules:
    - if: "$CI_COMMIT_TAG"
      when: on_success
